services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
        container_name: ruby_vote
        working_dir: /var/www
        volumes:
            - .:/var/www
            - bundle_cache:/bundle_cache
        environment:
            - BUNDLE_PATH=/bundle_cache
        ports:
            - 8091:3000
        networks:
            - app-networks
    mysql:
        image: mysql:8.0
        container_name: db-ruby
        ports:
            - 3313:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vote
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=2213
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/sql:/docker-entrypoint-initdb.d
        networks:
            - app-networks
    mailcatcher:
        container_name: ${PROJECT_NAME:-basic}_mailcatcher
        image: schickling/mailcatcher
        ports:
            - ${MAILCATCHER_PORT_EXTRA:-1089}:${MAILCATCHER_PORT_INBOUND:-1080}
            - ${MAILCATCHER_SMTP_PORT_EXTRA:-10250}:${MAILCATCHER_SMTP_PORT_INBOUND:-1025}
        networks:
            - app-networks
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: ruby_phpmyadmin
#        environment:
#            - PMA_ARBITRARY=1
#            - PMA_HOST=db-ruby
#            - PMA_USER=docker
#            - PMA_PASSWORD=docker
#        ports:
#            - 8081:80
#        networks:
#            - app-networks
volumes:
    bundle_cache:
networks:
    app-networks:
        driver: bridge
